config/routes.rb
Rails.application.routes.draw do
  get '/bookings', to: 'bookings#index'
  get '/user-bookings', to: 'bookings#user_bookings', as: 'user_bookings'
  delete "/booking/:id", to: 'bookings#destroy', as:'delete_booking'
  devise_for :users
  resources :events do
    resources :bookings, only: [:create]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "events#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.admin?
      can :manage, :all
    else
      can :read, Event
      can :book, Event
      can :create, Booking
      can :destroy, Booking
      can :user_bookings, Booking, user_id: user
      cannot :index, Booking
    end
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  enum status: { registered: 0, upcoming: 1 }
  has_many :bookings, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings, dependent: :destroy
  enum role: { user: 0, admin: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, alert: "You are not authorized to access this page."
  end

  rescue_from ActionController::InvalidAuthenticityToken, with: :handle_unauthenticated_access

  private

  def handle_unauthenticated_access
    # Redirect to the login page or do something else
    redirect_to new_user_session_path, alert: 'You need to sign in to access this page.'
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_booking, only: %i[ destroy ]

  def index
    @bookings = Booking.all
  end

  def user_bookings
    @bookings = current_user.bookings
  end

  def create
    @event = Event.find(params[:event_id])
    @user = User.find(params[:user_id])
    existing_booking = Booking.find_by(event_id: @event.id, user_id: @user.id)

    if existing_booking
      redirect_to root_path, alert: "You have already booked this event."
    else
      @booking = Booking.new(event: @event, user: @user)

      if @booking.save
        redirect_to user_bookings_path, notice: "You have booked #{@event.title}"
      end
    end
  end

  def destroy
    @booking.destroy!

    respond_to do |format|
      format.html { redirect_to user_bookings_path, notice: "Booking was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
  def set_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @events = Event.all

    apply_search_and_filters
  end

  def show
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @event.destroy!

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:title, :date, :location, :description, :status)
    end

    def apply_search_and_filters
      @events = @events.where('title LIKE ?', "%#{params[:title]}%") if params[:title].present?
      @events = @events.where(location: params[:location]) if params[:location].present?
      @events = @events.where(status: params[:status]) if params[:status].present?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/bookings/_booking.html.erb
<td> <%= booking.event.title %></td>
<td><%= booking.event.date %></td>
<td><%= button_to "Delete", delete_booking_path(booking.id), method: :delete %></td>

app/views/bookings/index.html.erb
<h1>Bookings</h1>
<% unless @bookings.empty? %>
  <table>
    <thead>
      <tr>
        <th>Event</th>
        <th>Date</th>
        <th>Name</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
      <% @bookings.each do |booking| %>
        <tr>
          <td><%= booking.event.title %></td>
          <td><%= booking.event.date %></td>
          <td><%= booking.user.name %></td>
          <td><%= booking.user.email %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h4>No events available currently</h4>
<% end %>

<%= button_to "Back to events", events_path, method: :get %>

app/views/bookings/new.html.erb
<h1>Book Event</h1>
<div>
  <%= @event.title %>
</div>
<%= form_with(model: [@event, @booking]) do |form| %>
  <% if @booking.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
        <% @booking.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <%= form.hidden_field :event_id, value: @event.id %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bookings/user_bookings.html.erb
<h1>Your Bookings</h1>
<p style="color: green"><%= notice %></p>
<% unless @bookings.empty? %>
  <table>
    <thead>
      <tr>
        <th>Event</th>
        <th>Date</th>
        <th>action</th>
      </tr>
    </thead>
    <tbody>
      <% @bookings.each do |booking| %>
        <tr>
          <%= render partial: 'booking', locals: { booking: booking } %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h4>No events available currently</h4>
<% end %>
<%= button_to "Back to events", events_path, method: :get %>

app/views/events/_event.html.erb
<tr id="<%= dom_id event %>">
  <td><%= event.title %></td>
  <td><%= event.date %></td>
  <td><%= event.location %></td>
  <td><%= event.description %></td>
  <td><%= event.status %></td>
  <td>
    <%= button_to "Book", event_bookings_path(event_id: event.id, user_id: current_user.id), method: :post %>
  </td>
</tr>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.select :status, Event.statuses.keys %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Show this event", @event %> |
  <%= button_to "Back to events", events_path, method: :get %>
</div>

app/views/events/index.html.erb
<% if user_signed_in? %>
  <p style="color: green"><%= notice %></p>
  <p style="color: red"><%= alert %></p>
  <h1>Events</h1>
  <div id="events">
    <p>Welcome, <%= current_user.name %></p>
    <%unless @events.empty?%>
    <div>
      <%= form_tag(events_path, method: :get) do %>
        <%= text_field_tag :title, params[:title], placeholder: 'Search by title' %>
        <%= select_tag :location, options_for_select(Event.pluck(:location).uniq, params[:location]), prompt: 'Filter by location' %>
        <%= select_tag :status, options_for_select(Event.statuses.keys, params[:status]), prompt: 'Filter by status' %>
        <%= submit_tag 'Search and Filter' %>
      <% end %>
      <table>
        <thead>
          <tr>
            <th>Title</th>
            <th>Date</th>
            <th>Location</th>
            <th>Description</th>
            <th>Status</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @events.each do |event| %>
            <%= render event %>
            <td><%= button_to "Show", event, method: :get %></td>
          <% end %>
        </tbody>
      </table>
    </div>
    <% else %>
      <h4>no events available currently</h4>
    <% end %>
  </div>
  <p>======================================================</p>
  <%= button_to 'Your Bookings', user_bookings_path, method: :get %>
  <% if can?(:create, Event) %>
    <%= button_to 'All Bookings', bookings_path, method: :get %>
    <%= button_to "New event", new_event_path, method: :get %>
  <% end %>
<% end %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= button_to "Back to events", events_path, method: :get %>
</div>

app/views/events/register_for_event.erb
<%= form_tag( 'path' , remote: true) do |f| %>
true
<% end %>

app/views/events/show.html.erb
<p style="color: green"><%= notice %></p>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Date</th>
      <th>Location</th>
      <th>Description</th>
      <th>Status</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <%= render @event %>
  </tbody>
</table>

<% if user_signed_in? %>
    <%= button_to "Back to events", events_path, method: :get %>
  <div>
    <% if can?(:create, Event) %>
      <%= button_to "Edit this event", edit_event_path(@event), method: :get %>
      <%= button_to "Destroy this event", @event, method: :delete %>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Event Management</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= button_to 'Logout', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= button_to 'Sign up', new_user_registration_path, method: :get %>
      <%= button_to 'Login', new_user_session_path, method: :get %>
    <% end %>
    <%= yield %>
  </body>
</html>